# Rubix Coding Challenge - Rubix Bakery

# This API has been developed using Serverless
# And is hosted on AWS as a lambda function

# Author: Renji Harold <renjiharold@nbnco.com.au>
# Started: 28 October 2018.


service: rubix-bakery

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: true

provider:
  name: aws
  runtime: python3.6
  stage: prod
  region: ap-southeast-2

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'